// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: userop.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 收藏相关消息
type UserFavRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId       int32                  `protobuf:"varint,2,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Pages         int32                  `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	PagePerNums   int32                  `protobuf:"varint,4,opt,name=pagePerNums,proto3" json:"pagePerNums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFavRequest) Reset() {
	*x = UserFavRequest{}
	mi := &file_userop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFavRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFavRequest) ProtoMessage() {}

func (x *UserFavRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFavRequest.ProtoReflect.Descriptor instead.
func (*UserFavRequest) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{0}
}

func (x *UserFavRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserFavRequest) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *UserFavRequest) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *UserFavRequest) GetPagePerNums() int32 {
	if x != nil {
		return x.PagePerNums
	}
	return 0
}

type FavListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*GoodsInfo           `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavListResponse) Reset() {
	*x = FavListResponse{}
	mi := &file_userop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavListResponse) ProtoMessage() {}

func (x *FavListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavListResponse.ProtoReflect.Descriptor instead.
func (*FavListResponse) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{1}
}

func (x *FavListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *FavListResponse) GetData() []*GoodsInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GoodsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ShopPrice     float32                `protobuf:"fixed32,3,opt,name=shopPrice,proto3" json:"shopPrice,omitempty"`
	GoodsBrief    string                 `protobuf:"bytes,4,opt,name=goodsBrief,proto3" json:"goodsBrief,omitempty"`
	Images        string                 `protobuf:"bytes,5,opt,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfo) Reset() {
	*x = GoodsInfo{}
	mi := &file_userop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfo) ProtoMessage() {}

func (x *GoodsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfo.ProtoReflect.Descriptor instead.
func (*GoodsInfo) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{2}
}

func (x *GoodsInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodsInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsInfo) GetShopPrice() float32 {
	if x != nil {
		return x.ShopPrice
	}
	return 0
}

func (x *GoodsInfo) GetGoodsBrief() string {
	if x != nil {
		return x.GoodsBrief
	}
	return ""
}

func (x *GoodsInfo) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

type IsFavResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFavResponse) Reset() {
	*x = IsFavResponse{}
	mi := &file_userop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFavResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFavResponse) ProtoMessage() {}

func (x *IsFavResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFavResponse.ProtoReflect.Descriptor instead.
func (*IsFavResponse) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{3}
}

func (x *IsFavResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 收货地址相关消息
type AddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressRequest) Reset() {
	*x = AddressRequest{}
	mi := &file_userop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressRequest) ProtoMessage() {}

func (x *AddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressRequest.ProtoReflect.Descriptor instead.
func (*AddressRequest) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{4}
}

func (x *AddressRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddressRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Province      string                 `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,5,opt,name=district,proto3" json:"district,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	SignerName    string                 `protobuf:"bytes,7,opt,name=signerName,proto3" json:"signerName,omitempty"`
	SignerMobile  string                 `protobuf:"bytes,8,opt,name=signerMobile,proto3" json:"signerMobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_userop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{5}
}

func (x *Address) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Address) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Address) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Address) GetSignerName() string {
	if x != nil {
		return x.SignerName
	}
	return ""
}

func (x *Address) GetSignerMobile() string {
	if x != nil {
		return x.SignerMobile
	}
	return ""
}

type AddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressResponse) Reset() {
	*x = AddressResponse{}
	mi := &file_userop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressResponse) ProtoMessage() {}

func (x *AddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressResponse.ProtoReflect.Descriptor instead.
func (*AddressResponse) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{6}
}

func (x *AddressResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddressListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*Address             `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressListResponse) Reset() {
	*x = AddressListResponse{}
	mi := &file_userop_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressListResponse) ProtoMessage() {}

func (x *AddressListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressListResponse.ProtoReflect.Descriptor instead.
func (*AddressListResponse) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{7}
}

func (x *AddressListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AddressListResponse) GetData() []*Address {
	if x != nil {
		return x.Data
	}
	return nil
}

// 留言相关消息
type MessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	MessageType   int32                  `protobuf:"varint,3,opt,name=messageType,proto3" json:"messageType,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	File          string                 `protobuf:"bytes,6,opt,name=file,proto3" json:"file,omitempty"`
	Pages         int32                  `protobuf:"varint,7,opt,name=pages,proto3" json:"pages,omitempty"`
	PagePerNums   int32                  `protobuf:"varint,8,opt,name=pagePerNums,proto3" json:"pagePerNums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	mi := &file_userop_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{8}
}

func (x *MessageRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MessageRequest) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *MessageRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *MessageRequest) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *MessageRequest) GetPagePerNums() int32 {
	if x != nil {
		return x.PagePerNums
	}
	return 0
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_userop_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{9}
}

func (x *MessageResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MessageListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*MessageInfo         `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageListResponse) Reset() {
	*x = MessageListResponse{}
	mi := &file_userop_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageListResponse) ProtoMessage() {}

func (x *MessageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageListResponse.ProtoReflect.Descriptor instead.
func (*MessageListResponse) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{10}
}

func (x *MessageListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MessageListResponse) GetData() []*MessageInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type MessageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	MessageType   int32                  `protobuf:"varint,3,opt,name=messageType,proto3" json:"messageType,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	File          string                 `protobuf:"bytes,6,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageInfo) Reset() {
	*x = MessageInfo{}
	mi := &file_userop_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageInfo) ProtoMessage() {}

func (x *MessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_userop_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageInfo.ProtoReflect.Descriptor instead.
func (*MessageInfo) Descriptor() ([]byte, []int) {
	return file_userop_proto_rawDescGZIP(), []int{11}
}

func (x *MessageInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MessageInfo) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *MessageInfo) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MessageInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageInfo) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

var File_userop_proto protoreflect.FileDescriptor

const file_userop_proto_rawDesc = "" +
	"\n" +
	"\fuserop.proto\x12\x06userop\x1a\x1bgoogle/protobuf/empty.proto\"z\n" +
	"\x0eUserFavRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x18\n" +
	"\agoodsId\x18\x02 \x01(\x05R\agoodsId\x12\x14\n" +
	"\x05pages\x18\x03 \x01(\x05R\x05pages\x12 \n" +
	"\vpagePerNums\x18\x04 \x01(\x05R\vpagePerNums\"N\n" +
	"\x0fFavListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12%\n" +
	"\x04data\x18\x02 \x03(\v2\x11.userop.GoodsInfoR\x04data\"\x85\x01\n" +
	"\tGoodsInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tshopPrice\x18\x03 \x01(\x02R\tshopPrice\x12\x1e\n" +
	"\n" +
	"goodsBrief\x18\x04 \x01(\tR\n" +
	"goodsBrief\x12\x16\n" +
	"\x06images\x18\x05 \x01(\tR\x06images\")\n" +
	"\rIsFavResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"8\n" +
	"\x0eAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\"\xdb\x01\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x1a\n" +
	"\bprovince\x18\x03 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x05 \x01(\tR\bdistrict\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x1e\n" +
	"\n" +
	"signerName\x18\a \x01(\tR\n" +
	"signerName\x12\"\n" +
	"\fsignerMobile\x18\b \x01(\tR\fsignerMobile\"!\n" +
	"\x0fAddressResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"P\n" +
	"\x13AddressListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12#\n" +
	"\x04data\x18\x02 \x03(\v2\x0f.userop.AddressR\x04data\"\xda\x01\n" +
	"\x0eMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12 \n" +
	"\vmessageType\x18\x03 \x01(\x05R\vmessageType\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x12\n" +
	"\x04file\x18\x06 \x01(\tR\x04file\x12\x14\n" +
	"\x05pages\x18\a \x01(\x05R\x05pages\x12 \n" +
	"\vpagePerNums\x18\b \x01(\x05R\vpagePerNums\"!\n" +
	"\x0fMessageResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"T\n" +
	"\x13MessageListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12'\n" +
	"\x04data\x18\x02 \x03(\v2\x13.userop.MessageInfoR\x04data\"\x9f\x01\n" +
	"\vMessageInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12 \n" +
	"\vmessageType\x18\x03 \x01(\x05R\vmessageType\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x12\n" +
	"\x04file\x18\x06 \x01(\tR\x04file2\xc5\x05\n" +
	"\x06UserOp\x12=\n" +
	"\n" +
	"GetFavList\x12\x16.userop.UserFavRequest\x1a\x17.userop.FavListResponse\x12<\n" +
	"\n" +
	"AddUserFav\x12\x16.userop.UserFavRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\rDeleteUserFav\x12\x16.userop.UserFavRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\x10GetUserFavDetail\x12\x16.userop.UserFavRequest\x1a\x16.google.protobuf.Empty\x126\n" +
	"\x05IsFav\x12\x16.userop.UserFavRequest\x1a\x15.userop.IsFavResponse\x12E\n" +
	"\x0eGetAddressList\x12\x16.userop.AddressRequest\x1a\x1b.userop.AddressListResponse\x129\n" +
	"\rCreateAddress\x12\x0f.userop.Address\x1a\x17.userop.AddressResponse\x128\n" +
	"\rUpdateAddress\x12\x0f.userop.Address\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\rDeleteAddress\x12\x16.userop.AddressRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\rCreateMessage\x12\x16.userop.MessageRequest\x1a\x17.userop.MessageResponse\x12B\n" +
	"\vMessageList\x12\x16.userop.MessageRequest\x1a\x1b.userop.MessageListResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_userop_proto_rawDescOnce sync.Once
	file_userop_proto_rawDescData []byte
)

func file_userop_proto_rawDescGZIP() []byte {
	file_userop_proto_rawDescOnce.Do(func() {
		file_userop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userop_proto_rawDesc), len(file_userop_proto_rawDesc)))
	})
	return file_userop_proto_rawDescData
}

var file_userop_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_userop_proto_goTypes = []any{
	(*UserFavRequest)(nil),      // 0: userop.UserFavRequest
	(*FavListResponse)(nil),     // 1: userop.FavListResponse
	(*GoodsInfo)(nil),           // 2: userop.GoodsInfo
	(*IsFavResponse)(nil),       // 3: userop.IsFavResponse
	(*AddressRequest)(nil),      // 4: userop.AddressRequest
	(*Address)(nil),             // 5: userop.Address
	(*AddressResponse)(nil),     // 6: userop.AddressResponse
	(*AddressListResponse)(nil), // 7: userop.AddressListResponse
	(*MessageRequest)(nil),      // 8: userop.MessageRequest
	(*MessageResponse)(nil),     // 9: userop.MessageResponse
	(*MessageListResponse)(nil), // 10: userop.MessageListResponse
	(*MessageInfo)(nil),         // 11: userop.MessageInfo
	(*emptypb.Empty)(nil),       // 12: google.protobuf.Empty
}
var file_userop_proto_depIdxs = []int32{
	2,  // 0: userop.FavListResponse.data:type_name -> userop.GoodsInfo
	5,  // 1: userop.AddressListResponse.data:type_name -> userop.Address
	11, // 2: userop.MessageListResponse.data:type_name -> userop.MessageInfo
	0,  // 3: userop.UserOp.GetFavList:input_type -> userop.UserFavRequest
	0,  // 4: userop.UserOp.AddUserFav:input_type -> userop.UserFavRequest
	0,  // 5: userop.UserOp.DeleteUserFav:input_type -> userop.UserFavRequest
	0,  // 6: userop.UserOp.GetUserFavDetail:input_type -> userop.UserFavRequest
	0,  // 7: userop.UserOp.IsFav:input_type -> userop.UserFavRequest
	4,  // 8: userop.UserOp.GetAddressList:input_type -> userop.AddressRequest
	5,  // 9: userop.UserOp.CreateAddress:input_type -> userop.Address
	5,  // 10: userop.UserOp.UpdateAddress:input_type -> userop.Address
	4,  // 11: userop.UserOp.DeleteAddress:input_type -> userop.AddressRequest
	8,  // 12: userop.UserOp.CreateMessage:input_type -> userop.MessageRequest
	8,  // 13: userop.UserOp.MessageList:input_type -> userop.MessageRequest
	1,  // 14: userop.UserOp.GetFavList:output_type -> userop.FavListResponse
	12, // 15: userop.UserOp.AddUserFav:output_type -> google.protobuf.Empty
	12, // 16: userop.UserOp.DeleteUserFav:output_type -> google.protobuf.Empty
	12, // 17: userop.UserOp.GetUserFavDetail:output_type -> google.protobuf.Empty
	3,  // 18: userop.UserOp.IsFav:output_type -> userop.IsFavResponse
	7,  // 19: userop.UserOp.GetAddressList:output_type -> userop.AddressListResponse
	6,  // 20: userop.UserOp.CreateAddress:output_type -> userop.AddressResponse
	12, // 21: userop.UserOp.UpdateAddress:output_type -> google.protobuf.Empty
	12, // 22: userop.UserOp.DeleteAddress:output_type -> google.protobuf.Empty
	9,  // 23: userop.UserOp.CreateMessage:output_type -> userop.MessageResponse
	10, // 24: userop.UserOp.MessageList:output_type -> userop.MessageListResponse
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_userop_proto_init() }
func file_userop_proto_init() {
	if File_userop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userop_proto_rawDesc), len(file_userop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userop_proto_goTypes,
		DependencyIndexes: file_userop_proto_depIdxs,
		MessageInfos:      file_userop_proto_msgTypes,
	}.Build()
	File_userop_proto = out.File
	file_userop_proto_goTypes = nil
	file_userop_proto_depIdxs = nil
}
