nacos:
  host: 192.168.1.2
  port: 8848
  namespace: 'a5d97b00-e809-4caf-bed8-35b20e99eb62'
  timeout: 5000
  logDir: './tmp/log'
  cacheDir: './tmp/cache'
  logLevel: 'debug'
  dataId: 'inventory_srv'
  group: 'dev'