# 服务配置示例文件
# 请复制此文件为 config-develop.yaml 并根据实际环境修改配置

# 服务配置
server:
  host: '0.0.0.0' # 服务监听地址
  port: 50051 # 服务监听端口
  name: 'user-srv' # 服务名称

# Consul配置
consul:
  host: '127.0.0.1' # Consul服务器地址
  port: 8500 # Consul服务器端口

# 数据库配置
db:
  host: '127.0.0.1' # 数据库服务器地址
  port: 3306 # 数据库端口
  user: 'root' # 数据库用户名
  password: '123456' # 数据库密码
  dbname: 'joyshop_user_srv' # 数据库名称
