nacos:
  host: 192.168.1.2
  port: 8848
  namespace: 'b1da278a-9f12-416e-9da9-7a2a87892d7e'
  timeout: 5000
  logDir: './tmp/log'
  cacheDir: './tmp/cache'
  logLevel: 'debug'
  dataId: 'user_srv'
  group: 'dev'
  username: 'nacos'
  password: 'nacos'
