nacos:
  host: 192.168.1.7
  port: 8848
  namespace: 'd14bd172-172e-43d4-a99d-559fcf636337'
  timeout: 5000
  logDir: './tmp/log'
  cacheDir: './tmp/cache'
  logLevel: 'debug'
  dataId: 'user_srv'
  group: 'dev'
  username: 'walker'
  password: 'walker123'
