nacos:
  host: 192.168.1.14
  port: 8848
  namespace: '1409f272-a09b-4656-89d0-eaa5f818cb0c'
  timeout: 5000
  logDir: './tmp/log'
  cacheDir: './tmp/cache'
  logLevel: 'debug'
  dataId: 'goods_srv'
  group: 'dev'